name: Cron Docker image integration

on:
  push:
    branches: [ "develop" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-cron -f Dockerfile-cron .

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Push to Docker Hub
        env:
          REPO: yeungjin-global-cron
        run:
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/$REPO
