name: Docker image integration

on:
  push:
    branches: [ "develop" ]

jobs:
  laravel_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-test .

  cron_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
        run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-cron -f Dockerfile-cron .

  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Push to Docker Hub
        env:
          REPO: yeungjin-global-test
        run:
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/$REPO
