name: Docker image integration

on:
  push:
    branches: [ "develop" ]

jobs:
  laravel_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-test .

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Push to Docker Hub
        run:
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-test

  cron_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-cron -f Dockerfile-cron .

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Push to Docker Hub
        run:
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-test
