name: Assign Issue Creator as Assignee

on:
  issues:
    types: [opened]

jobs:
  assign_issue_creator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get issue creator
      run: |
        ISSUE_CREATOR=$(curl -s -H "Authorization: Bearer ${{ secrets.ISSUE_TOKEN }}" "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" | jq -r '.user.login')
        echo "::set-output name=ISSUE_CREATOR::$ISSUE_CREATOR"

    - name: Assign issue creator as assignee
      run: |
        ISSUE_CREATOR="${{ steps.get_issue_creator.outputs.ISSUE_CREATOR }}"
        echo "Assigning issue creator $ISSUE_CREATOR as assignee..."
        curl -X POST -H "Authorization: Bearer ${{ secrets.ISSUE_TOKEN }}" -H "Content-Type: application/json" -d "{\"assignees\":[\"$ISSUE_CREATOR\"]}" "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees"
