name: 'Auto Assign'
on:
  pull_request:
    branches: 
      - develop

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          configuration-path: '.github/auto_assign.yml'
